# Generated by Django 6.0.3 on 2026-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_km',
            field=models.FloatField(default=15.0),
        ),
    ]
