# Generated by Django 6.0.3 on 2026-03-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
