# Generated by Django 6.0.3 on 2026-03-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_hour',
            field=models.FloatField(default=300.0),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_km',
            field=models.FloatField(default=12.0),
        ),
    ]
