# Generated by Django 6.0.3 on 2026-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_price_per_hour_alter_car_price_per_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_km', models.FloatField(default=15.0)),
                ('price_per_hour', models.FloatField(default=500.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='bikes/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
