# Generated by Django 6.0.3 on 2026-03-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_bikebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
