# Generated by Django 6.0.3 on 2026-03-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_bike_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='brand',
        ),
    ]
