# Generated by Django 6.0.3 on 2026-03-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_bike_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikebooking',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='bikebooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.DeleteModel(
            name='BikeBooking',
        ),
    ]
