# Generated by Django 6.0.3 on 2026-03-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_bikebooking_bike_remove_bikebooking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
