# Generated by Django 6.0.3 on 2026-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
